import { Livre } from "./livre";

export const LIVRES: Livre [ ] = [
    {
        id: 1,
        title: 'Le Petit Prince',
        resume: `L'enfant et le petit prince se retrouvent dans un univers magique où ils doivent s’entraider pour sauver le renard`,
        image: 'https://m.media-amazon.com/images/I/710wth0vXZL._AC_UF1000,1000_QL80_.jpg',
        author: 'Antoine de Saint-Exupéry',
        createdAt:  new Date('2005/03/14'),
        updatedAt: new Date('2005/09/01'),
        categories: [2, 3],
    },
    {
        id: 2,
        title: 'Star Wars: L\'integrale',
        resume: `L'action de ces films se déroule « dans une galaxie lointaine, très lointaine » où les humains cohabitent avec de nombreuses espèces extraterrestres, à une époque indéterminéec. La trame repose sur l'affrontement entre les chevaliers Jedi et leurs rivaux, les seigneurs Sith. `,
        image: 'https://assets.bubblebd.com/img/oul6udcpva/vqo24hnp1t.jpg',
        author: 'George Lucas',
        createdAt: new Date('1977/09/18'),
        updatedAt: new Date('2019/01/01'),
        categories: [1, 2, 3],
    },
    {
        id: 3,
        title: 'Harry Potter et la Pierre Philosophique',
        resume: `Harry potter se met a la recherche du dernier orcrux existant, la fameuse pierre philosophique`,
        image: 'https://m.media-amazon.com/images/I/516qWQcG3FL.jpg',
        author: 'J.K. Rowlings',
        createdAt: new Date('1999/01/01'),
        updatedAt: new Date('1997/06/23'),
        categories: [1, 4],
    },
    {
        id: 4,
        title: 'L\'Alliance Gauloise',
        resume: `Alliance gauloise comme les cigarettes et tout`,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCOeDlj06LVWXFJmHKSM0NleA0HCwus86w2ORyz8hjyA&s',
        author: 'Alexandre Dumas',
        createdAt: new Date('1885/01/01'),
        updatedAt: new Date('1885/01/01'),
        categories: [5],
    },
    {
        id: 5,
        title: 'Une Vie en Hiver',
        resume: `Aucune foutu idee de ce que c'est que ce livre de kassos`,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbsiEtpjv86gH4eCG1Jur14GsVZVq77eq8BZYksAX7lw&s',
        author: 'Mikhail Bulgakov',
        createdAt: new Date('1927/01/25'),
        updatedAt: new Date('1985/01/01'),
        categories: [2],
    },
    {
        id: 6,
        title: 'La Dernière Tentation du Christ',
        resume: `test du text genre loreml ipsum del raiudteu poehbiufbie`,
        image: 'https://m.media-amazon.com/images/I/81HtNQVpTWL._AC_UF1000,1000_QL80_.jpg',
        author: 'Christian Ingerslev',
        createdAt: new Date('2017/09/18'),
        updatedAt: new Date('2019/01/01'),
        categories: [6],
    },
]
