import { Page } from "./page";

export const PAGES: Page [ ] = [
    {
        id: 1,
        title: 'Chapitre 1: La Menace fantôme',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Integer ac tellus eu metus suscipit tincidunt non ac turpis. Nulla facilisi. Vestibulum fermentum mi vel massa aliquam, in euismod elit tristique. Cras id libero eget felis consequat ultricies sit amet eget odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed condimentum euismod neque id luctus. Fusce condimentum, est id fermentum ultrices, lorem arcu suscipit nunc, non tristique elit velit id ante. Quisque eu felis tincidunt, lobortis elit vel, tincidunt metus. Duis non augue id risus luctus dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean nec ligula non mi fermentum egestas. Duis eu massa ac ligula egestas pretium.`,
        createdAt:  new Date('2005/03/14'),
        updatedAt: new Date('2005/09/01'),
        id_livre: 2,
    },
    {
        id: 2,
        title: 'Chapitre 2: L\'Attaque des clones',
        content: `Vivamus sed ligula et tortor mattis auctor ac a lectus. Duis vitae nisi in nulla varius tempor non eget dolor. Donec ut ligula eu nunc placerat convallis. Duis in magna at lacus scelerisque accumsan. Cras eget libero sed ipsum condimentum efficitur. Proin vitae mauris justo. Fusce id lacus at quam efficitur dictum nec vel dolor. Maecenas finibus urna ac malesuada fringilla.`,
        createdAt: new Date('2017/09/18'),
        updatedAt: new Date('2019/01/01'),
        id_livre: 2,
    },
    {
        id: 3,
        title: 'Chapitre 3:  La Revanche des Sith',
        content: `Phasellus sodales nisi nec libero tristique, non condimentum ipsum viverra. Curabitur vitae nunc eget libero condimentum volutpat. Phasellus feugiat velit eu orci tempus, nec dictum massa aliquet. Nullam varius justo non est sodales commodo. In auctor fermentum justo, at varius metus viverra a. Aliquam erat volutpat. Integer eget enim vitae nulla lacinia congue et et est. Phasellus ac justo quis augue pharetra cursus. Suspendisse potenti. Sed at placerat erat, vel rutrum ipsum. Nam in sapien ligula.`,
        createdAt: new Date('1999/01/01'),
        updatedAt: new Date('1997/06/23'),
        id_livre: 2,
    },
    {
        id: 4,
        title: 'Chapitre 4: Un nouvel espoir',
        content: `Sed viverra, felis a laoreet gravida, elit purus consequat ex, at pulvinar dui purus vel sapien. In ut mi ut lectus scelerisque faucibus. Mauris convallis consequat tortor, ac consequat sapien vulputate in. In hac habitasse platea dictumst. Vivamus nec libero non nulla malesuada faucibus. Curabitur non mauris vel dolor viverra viverra vel sed mauris. Donec nec dictum lorem.`,
        createdAt: new Date('1885/01/01'),
        updatedAt: new Date('1885/01/01'),
        id_livre: 2,
    },
    {
        id: 5,
        title: 'Chapitre 5:  L\'Empire contre-attaque',
        content: `Nunc ultrices sagittis ligula, ac molestie enim aliquet nec. Sed nec commodo velit. Donec ultrices hendrerit sem. Sed vitae tellus sed purus fringilla congue. Nulla facilisi. Duis vitae ex id mi lacinia laoreet a sit amet sapien. Sed commodo ante eget turpis pharetra, nec vestibulum felis ultrices. Vivamus vel libero sapien. Etiam pellentesque, dolor nec consequat dignissim, tortor elit lobortis eros, eget commodo nunc est non magna. Sed vehicula turpis non velit commodo, a aliquet felis ultricies.`,
        createdAt: new Date('1927/01/25'),
        updatedAt: new Date('1985/01/01'),
        id_livre: 2,
    },
    {
        id: 6,
        title: 'Chapitre 1: La rencontre',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Integer ac tellus eu metus suscipit tincidunt non ac turpis. Nulla facilisi. Vestibulum fermentum mi vel massa aliquam, in euismod elit tristique. Cras id libero eget felis consequat ultricies sit amet eget odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed condimentum euismod neque id luctus. Fusce condimentum, est id fermentum ultrices, lorem arcu suscipit nunc, non tristique elit velit id ante. Quisque eu felis tincidunt, lobortis elit vel, tincidunt metus. Duis non augue id risus luctus dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean nec ligula non mi fermentum egestas. Duis eu massa ac ligula egestas pretium.`,
        createdAt:  new Date('2005/03/14'),
        updatedAt: new Date('2005/09/01'),
        id_livre: 1,
    },
    {
        id: 7,
        title: 'Chapitre 2: Le debut du voyage',
        content: `Vivamus sed ligula et tortor mattis auctor ac a lectus. Duis vitae nisi in nulla varius tempor non eget dolor. Donec ut ligula eu nunc placerat convallis. Duis in magna at lacus scelerisque accumsan. Cras eget libero sed ipsum condimentum efficitur. Proin vitae mauris justo. Fusce id lacus at quam efficitur dictum nec vel dolor. Maecenas finibus urna ac malesuada fringilla.`,
        createdAt: new Date('2017/09/18'),
        updatedAt: new Date('2019/01/01'),
        id_livre: 1,
    },
    {
        id: 8,
        title: 'Chapitre 3:  Une amitié mouvementé',
        content: `Phasellus sodales nisi nec libero tristique, non condimentum ipsum viverra. Curabitur vitae nunc eget libero condimentum volutpat. Phasellus feugiat velit eu orci tempus, nec dictum massa aliquet. Nullam varius justo non est sodales commodo. In auctor fermentum justo, at varius metus viverra a. Aliquam erat volutpat. Integer eget enim vitae nulla lacinia congue et et est. Phasellus ac justo quis augue pharetra cursus. Suspendisse potenti. Sed at placerat erat, vel rutrum ipsum. Nam in sapien ligula.`,
        createdAt: new Date('1999/01/01'),
        updatedAt: new Date('1997/06/23'),
        id_livre: 1,
    },
    {
        id: 9,
        title: 'Chapitre 4: Un amour imposible',
        content: `Sed viverra, felis a laoreet gravida, elit purus consequat ex, at pulvinar dui purus vel sapien. In ut mi ut lectus scelerisque faucibus. Mauris convallis consequat tortor, ac consequat sapien vulputate in. In hac habitasse platea dictumst. Vivamus nec libero non nulla malesuada faucibus. Curabitur non mauris vel dolor viverra viverra vel sed mauris. Donec nec dictum lorem.`,
        createdAt: new Date('1885/01/01'),
        updatedAt: new Date('1885/01/01'),
        id_livre: 1,
    },
    {
        id: 10,
        title: 'Chapitre 5:  La confrontation finale',
        content: `Nunc ultrices sagittis ligula, ac molestie enim aliquet nec. Sed nec commodo velit. Donec ultrices hendrerit sem. Sed vitae tellus sed purus fringilla congue. Nulla facilisi. Duis vitae ex id mi lacinia laoreet a sit amet sapien. Sed commodo ante eget turpis pharetra, nec vestibulum felis ultrices. Vivamus vel libero sapien. Etiam pellentesque, dolor nec consequat dignissim, tortor elit lobortis eros, eget commodo nunc est non magna. Sed vehicula turpis non velit commodo, a aliquet felis ultricies.`,
        createdAt: new Date('1927/01/25'),
        updatedAt: new Date('1985/01/01'),
        id_livre: 12,
    },
    {
        id: 11,
        title: 'Chapitre 6: Le Retour du Jedi',
        content: `Sed elementum ultricies justo, et volutpat nisi molestie id. In hac habitasse platea dictumst. Vestibulum id mauris eu urna elementum efficitur. Vivamus in lorem sed purus venenatis varius sit amet non urna. Nam non nunc id metus ultricies pharetra. Nam pharetra dapibus ipsum vel molestie. Suspendisse potenti. Vivamus tempus lorem sed tellus sollicitudin, in tristique ligula lacinia. Maecenas tristique, arcu sit amet volutpat feugiat, est dui auctor nisi, et gravida nulla sem non nulla. Sed nec orci efficitur, accumsan metus in, vehicula metus. Maecenas non quam nec enim facilisis aliquet. Suspendisse nec elit eget arcu posuere accumsan id sit amet ligula. Sed condimentum, ligula non sollicitudin euismod, arcu quam sollicitudin risus, ac faucibus felis sem ut sem. Curabitur ullamcorper purus nec dolor fermentum molestie. Etiam vitae efficitur velit. Sed ac elit ultricies, lobortis elit nec, pharetra turpis. Vivamus a enim eget neque laoreet sodales. Integer ut ligula eu mauris varius consectetur.`,
        createdAt: new Date('1927/01/25'),
        updatedAt: new Date('1985/01/01'),
        id_livre: 2,
    },

]
